Update patch set 14
Patch Set 14: Code-Review-1

(1 comment)

@Abhishek, I tried running the home-webcomponent in my local using simple "ng serve" command after performing all build commands successfully. But I receive below error. 

As suggested on the README file, please add how to run the workbench application, so that others can run in their local machine before starting development.

-------Error after trying "ng serve"---------
ERROR in ./node_modules/ionicons/scss/ionicons.scss (./node_modules/@angular-devkit/build-angular/src/angular-cli-files/plugins/raw-css-loader.js!./node_modules/postcss-loader/lib??embedded!./node_modules/sass-loader/lib/loader.js??ref--14-3!./node_modules/ionicons/scss/ionicons.scss)
Module build failed (from ./node_modules/sass-loader/lib/loader.js):
Error: Node Sass does not yet support your current environment: OS X 64-bit with Unsupported runtime (67)
For more information on which environments are supported please see:
https://github.com/sass/node-sass/releases/tag/v4.9.3
    at module.exports (/Users/talasila/workbench/home-webcomponent/src/main/resources/node_modules/node-sass/lib/binding.js:13:13)

Patch-set: 14
Reviewer: Gerrit User 3 <3@655300a2-7a56-4504-9153-881edd907bea>
Label: Code-Review=-1